name: Makefile CI

on:
  push:
    branches: [ "master" ]

jobs:
  build:
    environment: Deployment
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Store ssh config
      env:
        SSH_CONFIG: ${{ secrets.SSH_CONFIG }}
      run: |
        mkdir -p ~/.ssh
        chmod 700 ~/.ssh
        echo "$SSH_CONFIG" > ~/.ssh/config
        ssh-keyscan $(grep Hostname ~/.ssh/config | cut -b 14-) >> ~/.ssh/known_hosts
        wc ~/.ssh/config
    - name: Generate
      run: make generate
    - name: Deploy
      run: make deploy
